name: Deploy Terraform on EC2

on:
  push:
    branches:
      - main  # Adjust if needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: velpuriv/AutomatePipeline
          ref: main

      - name: Ensure Terraform Directory Exists on EC2
        run: mkdir -p ~/terraform

      - name: Copy Terraform Files to EC2
        run: |
          rsync -av --delete terraform/ ~/terraform/

      - name: Initialize Terraform
        run: |
          cd ~/terraform
          terraform init

      - name: Apply Terraform Configuration
        run: |
          cd ~/terraform
          terraform apply -auto-approve
